# -*- coding: utf-8 -*-
"""Neural Network from Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEl73Rwx04NnsehSNlcX3ZBGN4lnr3W0
"""

from google.colab import files
uploaded = files.upload()   # Upload train.csv manually

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv("train.csv")
data.head()

data = np.array(data)
m,n = data.shape
np.random.shuffle(data)
data_dev = data[0:1000]
X_dev = data_dev[:, 1:].T
Y_dev = data_dev[:, 0]

data_train = data[1000:m]
X_train = data_train[:, 1:].T
Y_train = data_train[:, 0]

X_train = X_train / 255.0
X_dev = X_dev / 255.0

Y_train

X_train[:, 0].shape

import numpy as np

def init_params():
  w1 = np.random.rand(128, 784) - 0.5
  b1 = np.random.rand(128, 1) - 0.5
  w2 = np.random.rand(10, 128) - 0.5
  b2 = np.random.rand(10, 1) - 0.5
  return w1,b1,w2,b2

def ReLU(Z):
    return np.maximum(0,Z)

def Softmax(Z):
    Z = Z - np.max(Z, axis=0, keepdims=True)
    exp_Z = np.exp(Z)
    return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)

def forward_propagation(w1,b1,w2,b2,X):
    Z1 = w1.dot(X) + b1
    a1 = ReLU(Z1)
    Z2 = w2.dot(a1) + b2
    a2 = Softmax(Z2)
    return Z1,a1,Z2,a2

def one_hot(Y):
    num_classes = Y.max() + 1
    m = Y.size
    one_hot_Y = np.zeros((num_classes, m))
    one_hot_Y[Y, np.arange(m)] = 1
    return one_hot_Y

def deriv_ReLU(Z):
    return (Z > 0).astype(float)

def backward_propagation(Z1,a1,Z2,a2,w1,w2,X,Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = a2 - one_hot_Y
    dw2 = 1 / m * dZ2.dot(a1.T)
    db2 = 1 / m * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = w2.T.dot(dZ2) * deriv_ReLU(Z1)
    dw1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, axis=1, keepdims=True)
    return dw1,db1,dw2,db2

def update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
    w1 = w1 - alpha * dw1
    b1 = b1 - alpha * db1
    w2 = w2 - alpha * dw2
    b2 = b2 - alpha * db2
    return w1,b1,w2,b2

print(X_train.shape)  # should be (784, num_samples)

def get_accuracy(predictions, Y):
    return np.sum(predictions == Y) / Y.size

def get_predictions(a2):
    return np.argmax(a2, axis=0)

def gradient_descent(X, Y, iterations, alpha):
    w1, b1, w2, b2 = init_params()
    for i in range(iterations):
        Z1, a1, Z2, a2 = forward_propagation(w1, b1, w2, b2, X)
        dw1, db1, dw2, db2 = backward_propagation(Z1, a1, Z2, a2, w1, w2, X, Y)
        w1, b1, w2, b2 = update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, alpha)
        if i % 10 == 0:
            print("Iteration:", i)
            print("Accuracy:", get_accuracy(get_predictions(a2), Y))
    return w1, b1, w2, b2

w1,b1,w2,b2 = gradient_descent(X_train,Y_train,500,0.1)

import matplotlib.pyplot as plt
import numpy as np

def gradient_descent(X, Y, iterations, alpha):
    w1, b1, w2, b2 = init_params()
    accuracies = []

    for i in range(iterations):
        Z1, a1, Z2, a2 = forward_propagation(w1, b1, w2, b2, X)
        dw1, db1, dw2, db2 = backward_propagation(Z1, a1, Z2, a2, w1, w2, X, Y)
        w1, b1, w2, b2 = update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, alpha)

        pred = get_predictions(a2)
        acc = get_accuracy(pred, Y)
        accuracies.append(acc)

        if i % 10 == 0:
            print(f"Iteration: {i}, Accuracy: {acc:.4f}")

    return w1, b1, w2, b2, accuracies

w1, b1, w2, b2, accuracies = gradient_descent(X_train, Y_train, 500, 0.1)

plt.figure(figsize=(10,6))
plt.plot(range(len(accuracies)), accuracies, label="Training Accuracy")
plt.xlabel("Iteration")
plt.ylabel("Accuracy")
plt.title("Accuracy vs Iterations")
plt.grid(True)
plt.legend()
plt.show()